[package]
name = "SaveSyncd"
version = "0.1.0"
edition = "2021"

[dependencies]
ws = { package = "rocket_ws", version = "0.1.1" }
glob = "0.3.2"
rocket = "0.5.1"
serde = "1.0.219"
serde_json = "1.0.142"
sha256 = "1.6.0"
