name: Build
on:
  push:
    branches: [ master ]

env:
  dev_tag: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt install -y \
            libgtk-3-dev \
            libxdo-dev \
            libappindicator3-dev

      - name: Build
        run: cargo build --release

      - uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: ${{ env.dev_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Create New Latest Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.dev_tag }}
          tag_exists_error: false
          github_token: ${{ secrets.REPO_TOKEN }}
          message: "Latest Release"

      - name: Create Release
        continue-on-error: true
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body: Automatic release from master
          files: |
            target/release/SaveSyncd
          tag_name: ${{ env.dev_tag }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executable
          path: |
            target/release/SaveSyncd
          if-no-files-found: warn